### PR TITLE
Milestone5: Add style to the project

### PR DESCRIPTION
**Pull request by isume295**
In this milestone I:

- Added style to the project

### CODE REVIEW

**Review by laiifuu — CHANGES_REQUESTED** [review]
# STATUS: CHANGES REQUIRED :recycle: 

## Hi @isume295 :wave: 

Good job so far! Your project is looking great :fire: 
There are a couple of things that you still need to work on but you are almost there!
so-close

## Highlights
- [x] Amazing UI and great attention to details :fire: 
- [x] Nice initiative to learn new libraries :smiley: 

## Required Changes ♻️
- [ ] Although you added the CSS declarations for the font families used in the design, you still need to import those font families from a source, considering they might not be installed on another user's computer. 
The way you do this is by going to [Google Fonts](https://fonts.google.com/) and looking for the necessary font families, in this case, `Montserrat` and `Robotoslab`.
Once you find them you'll select the necessary font weights, then copy the links which will be prompted after you select the font weights into the head of your `index.html` file.

- [ ] As stated in the [requirements](https://github.com/microverseinc/curriculum-react-redux/blob/main/bookstore/styling.md#:~:text=Add%20any%20missing%20JSX%20elements%20to%20your%20project%20(without%20adding%20extra%20functionality)), you should add a component for the category in the `Add book` form, there will be no need to add any functionality to it. 
Screenshot from 2023-06-17 19-05-18


_Check the comments under the review. :point_down:_

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by isume295** [comment]
okay, thank you very much

**Comment by laiifuu** [comment]
Hi again, i know I wrote component, but yes it is just an input , sorry about that 🙏

**Comment by isume295** [comment]
it's okay, but I changed the addbook logic  to add the component as you suggested

**Review by peterrobert — APPROVED** [review]
Hi @isume295, 


### Highlights!

[ ] Good feature branch name ✔️
[ ] Descriptive pull request ✔️
[ ] Great work on your UI it looks amaizing✔️

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread or tag me @peterrobert if something is not 100% clear.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have only 3 code reviews per project. If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Pull request merged**
